# Generated by Django 5.1.1 on 2024-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movie_count',
            field=models.IntegerField(default=0),
        ),
    ]
