# Generated by Django 5.1.1 on 2024-10-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_director_movie_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie_count',
        ),
    ]
